/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdeaRouteImport } from './routes/idea'
import { Route as IndexRouteImport } from './routes/index'

const IdeaRoute = IdeaRouteImport.update({
  id: '/idea',
  path: '/idea',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/idea': typeof IdeaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/idea': typeof IdeaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/idea': typeof IdeaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/idea'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/idea'
  id: '__root__' | '/' | '/idea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeaRoute: typeof IdeaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/idea': {
      id: '/idea'
      path: '/idea'
      fullPath: '/idea'
      preLoaderRoute: typeof IdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeaRoute: IdeaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
